### ISSUE TITLE
Actualizar documentación

### ISSUE THREAD

**Issue by rubenfonnegra** [SnNig1/surgeries_repository#2]
Actualizar la documentación teniendo en cuenta el ```README.md``` que te puse en el pull request. Hay cosas adicionales que puedes añadir, y que no necesariamente tienes que realizar de inmediato, pero creo que lo que está allí es lo mínimo para documentar bien el repositorio.

**Comment by SnNig1** [comment]
Se actualizó el README.md, se agregaron imágenes de la vista de usuario, y la consulta de una cirugía, se actualizó los requisitos necesarios para el despliegue del software y las variables de entorno, se añadió el correo institucional y personal
